### ISSUE TITLE
Update links to examples in blog post

### ISSUE THREAD

**Issue by 4Giedrius** [raml-org/raml-website#12]
It looks like after merge somebody forgot to update links in website. 
Update all links in [newest blog post](http://raml.org/blogs/announcing-raml-10-ga) and change `raml-10` to `master`.

https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#defining-examples-in-raml ---> https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#defining-examples-in-raml

**Comment by sichvoge** [comment]
should be done! thanks
