### ISSUE TITLE
Strange example on RAML website

### ISSUE THREAD

**Issue by DataGreed** [raml-org/raml-website#15]
Here is a confusing example of resourceType usage - http://raml.org/developers/whats-new-raml-10

It features using of some kind of magical symbol `>`:

```
resourceTypes:

  ###############
  # Collection:
  ###############

  collection:
    get:
      responses:
        200:
          body:
            properties:
              total:
                type: number
                required: true
              members: >[]
    post:
      body:
        type: >
      responses:
        201:
          headers:
            Location:
              required: true
          body:
            type: >
```

I could not find anything about that in a specification (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#resource-types-and-traits)

Is it some kind of depricated syntax?

**Comment by sichvoge** [comment]
Thanks @DataGreed. I'll fix that as soon as possible. There were some problems with the framework I couldn't fix so far :)

**Comment by sichvoge** [comment]
BTW, I am closing it since I remembered I raised it in #13 already. Lets keep only one issue ;)
