### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by jcenturion** [raml-org/raml-website#3]
It seems to be that `jQuery` is not being loaded.

<img width="1152" alt="screen shot 2015-11-05 at 11 23 04 am" src="https://cloud.githubusercontent.com/assets/302314/10970838/de89e448-83af-11e5-8cbc-2d8015b6ae7d.png">

**Comment by mikestowe** [comment]
Can you please try again?  If still not working, can you let me know what browser (type and version) you are using so we can try to reproduce.  Thanks!

**Comment by marksou** [comment]
Working for me on latest Chrome and Firefox (Windows 64Bit). Projects don't display at all on IE9.
