### ISSUE TITLE
Design Your API Section: Description for API Workbench Wrong?

### ISSUE THREAD

**Issue by sshaw** [raml-org/raml-website#5]
[The API Workbench section](http://raml.org/developers/design-your-api) says that it's capable of

>  ... server generation, client generation, and even test capabilities all from a single, light-weight utility.

Though after downloading and using it, a well as looking through [their docs](http://apiworkbench.com/docs/), this functionality does not appear to be offered.

**Comment by sichvoge** [comment]
@sshaw you were right about these and you might have seen already things on what we are working on ;)

We corrected that mistake, but be assured - at some point you will see them back. ;)

Closing that.
